# Generated by Django 5.2.6 on 2025-09-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='zoom_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
