# Generated by Django 5.2.6 on 2025-09-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_event_zoom_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='entry',
            field=models.TextField(blank=True, null=True),
        ),
    ]
