# Generated by Django 5.2.6 on 2025-10-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='unique_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
