# Generated by Django 5.2.6 on 2025-10-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_profile_country_profile_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
